- name: play level variables
  hosts: local
  connection: local
  vars_files:
  - course.yaml

  tasks:
  - name: print the info
    ansible.builtin.debug:
      msg: "COURSE name is: {{ COURSE }}, DURATION is: {{ DURATIONS }}, TRAINER is: {{ TRAINER }}"